// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: game_sessions.sql

package dbmodels

import (
	"context"
	"database/sql"
)

const createGameSession = `-- name: CreateGameSession :execresult
INSERT INTO game_sessions (
    name, token, credits
) VALUES (?, ?, ?)
`

type CreateGameSessionParams struct {
	Name    sql.NullString
	Token   string
	Credits int32
}

func (q *Queries) CreateGameSession(ctx context.Context, arg CreateGameSessionParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createGameSession, arg.Name, arg.Token, arg.Credits)
}

const deleteGameSession = `-- name: DeleteGameSession :exec
UPDATE game_sessions
SET deleted_at = NOW()
WHERE id = ?
`

func (q *Queries) DeleteGameSession(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteGameSession, id)
	return err
}

const getGameSession = `-- name: GetGameSession :one
SELECT id, name, token, credits, created_at, updated_at, deleted_at FROM game_sessions
WHERE id = ? AND deleted_at IS NULL LIMIT 1
`

func (q *Queries) GetGameSession(ctx context.Context, id int64) (GameSession, error) {
	row := q.db.QueryRowContext(ctx, getGameSession, id)
	var i GameSession
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Token,
		&i.Credits,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
