// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: game_sessions.sql

package dbmodels

import (
	"context"
	"database/sql"
)

const addCreditsToSession = `-- name: AddCreditsToSession :execresult
UPDATE game_sessions
SET credits = credits + ?
WHERE token = ? AND deleted_at IS NULL
`

type AddCreditsToSessionParams struct {
	Credits int32
	Token   string
}

func (q *Queries) AddCreditsToSession(ctx context.Context, arg AddCreditsToSessionParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, addCreditsToSession, arg.Credits, arg.Token)
}

const createGameSession = `-- name: CreateGameSession :execresult
INSERT INTO game_sessions (
    name, token, credits
) VALUES (?, ?, ?)
`

type CreateGameSessionParams struct {
	Name    sql.NullString
	Token   string
	Credits int32
}

func (q *Queries) CreateGameSession(ctx context.Context, arg CreateGameSessionParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createGameSession, arg.Name, arg.Token, arg.Credits)
}

const deleteGameSessionByToken = `-- name: DeleteGameSessionByToken :execresult
UPDATE game_sessions
SET deleted_at = NOW()
WHERE token = ? AND deleted_at IS NULL
`

func (q *Queries) DeleteGameSessionByToken(ctx context.Context, token string) (sql.Result, error) {
	return q.db.ExecContext(ctx, deleteGameSessionByToken, token)
}

const getGameSessionByToken = `-- name: GetGameSessionByToken :one
SELECT id, name, token, credits, created_at, updated_at, deleted_at FROM game_sessions
WHERE token = ? AND deleted_at IS NULL LIMIT 1
`

func (q *Queries) GetGameSessionByToken(ctx context.Context, token string) (GameSession, error) {
	row := q.db.QueryRowContext(ctx, getGameSessionByToken, token)
	var i GameSession
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Token,
		&i.Credits,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const subtractCreditsFromSession = `-- name: SubtractCreditsFromSession :execresult
UPDATE game_sessions
SET credits = credits - ?
WHERE token = ? AND deleted_at IS NULL AND credits >= ?
`

type SubtractCreditsFromSessionParams struct {
	Credits   int32
	Token     string
	Credits_2 int32
}

func (q *Queries) SubtractCreditsFromSession(ctx context.Context, arg SubtractCreditsFromSessionParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, subtractCreditsFromSession, arg.Credits, arg.Token, arg.Credits_2)
}
