// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package dbmodels

import (
	"database/sql"
)

type User struct {
	ID                   int64
	FirstName            string
	LastName             string
	Avatar               sql.NullString
	Email                sql.NullString
	Password             sql.NullString
	MobileNumber         sql.NullString
	RegistrationMethodID int32
	Status               sql.NullBool
	CreatedAt            sql.NullTime
	UpdatedAt            sql.NullTime
	DeletedAt            sql.NullTime
}

type UserRegistrationMethod struct {
	ID          int64
	Name        string
	Description sql.NullString
}
