// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package dbmodels

import (
	"database/sql"
)

type GameSession struct {
	ID        int64
	Name      sql.NullString
	Token     string
	Credits   int32
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
	DeletedAt sql.NullTime
}
