// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: users.sql

package dbmodels

import (
	"context"
	"database/sql"
)

const createUserWithEmail = `-- name: CreateUserWithEmail :execresult
INSERT INTO users (
  first_name, last_name, email, registration_method_id
) VALUES (
  ?, ?, ?, ?
)
`

type CreateUserWithEmailParams struct {
	FirstName            string
	LastName             string
	Email                sql.NullString
	RegistrationMethodID int32
}

func (q *Queries) CreateUserWithEmail(ctx context.Context, arg CreateUserWithEmailParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createUserWithEmail,
		arg.FirstName,
		arg.LastName,
		arg.Email,
		arg.RegistrationMethodID,
	)
}

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM users
WHERE id = ?
`

func (q *Queries) DeleteUser(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteUser, id)
	return err
}

const getUser = `-- name: GetUser :one
SELECT id, first_name, last_name, avatar, email, password, mobile_number, registration_method_id, status, created_at, updated_at, deleted_at FROM users 
WHERE id = ? LIMIT 1
`

func (q *Queries) GetUser(ctx context.Context, id int64) (User, error) {
	row := q.db.QueryRowContext(ctx, getUser, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.FirstName,
		&i.LastName,
		&i.Avatar,
		&i.Email,
		&i.Password,
		&i.MobileNumber,
		&i.RegistrationMethodID,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getUsers = `-- name: GetUsers :many
SELECT id, first_name, last_name, avatar, email, password, mobile_number, registration_method_id, status, created_at, updated_at, deleted_at FROM users 
ORDER BY first_name
`

func (q *Queries) GetUsers(ctx context.Context) ([]User, error) {
	rows, err := q.db.QueryContext(ctx, getUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.FirstName,
			&i.LastName,
			&i.Avatar,
			&i.Email,
			&i.Password,
			&i.MobileNumber,
			&i.RegistrationMethodID,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
